### ISSUE TITLE
Convert memory bytes to human readable bytes

### ISSUE THREAD

**Issue by ghost** [Souravgoswami/linux_stat#7]
Hello. I want to convert memory bytes to human readable bytes like MB and GB. 
Is this possible? I have tried with some gems to convert memory size to human readable byte but I couldn't success.

**Comment by Souravgoswami** [comment]
Although LinuxStat's functionality is not that, but it's required so often that we have created a module called PrettifyBytes just for that purpose.

Here are some examples:
```
LS::PrettifyBytes.convert_decimal(1000)
=> "1.00 kilobyte"
LS::PrettifyBytes.convert_decimal(1024)
=> "1.02 kilobytes"
LS::PrettifyBytes.convert_short_decimal(1000)
=> "1.00 kB"
LS::PrettifyBytes.convert_short_decimal(1024)
=> "1.02 kB"

LS::PrettifyBytes.convert_decimal(3.14 * 1e9)
=> "3.14 gigabytes"

LS::PrettifyBytes.convert_decimal(3.14 * 1e8)
=> "314.00 megabytes"

LS::PrettifyBytes.convert_binary(2000)
=> "1.95 kibibytes"
LS::PrettifyBytes.convert_binary(1024)
=> "1.00 kibibyte"
 LS::PrettifyBytes.convert_short_binary(2000)
=> "1.95 KiB"
LS::PrettifyBytes.convert_short_binary(1024)
=> "1.00 KiB"
```

P.S.: You shouldn't definitely use a big gem like LS that also needs a compiler to build native binary just to use PrettifyBytes. Instead, you can see the code in PrettifyBytes here:

https://github.com/Souravgoswami/linux_stat/blob/master/lib/linux_stat/prettify_bytes.rb

**Comment by ghost** [comment]
Thank you. I want to get the available memory from LS and convert them into GB or MB, but when I tried to convert them into GB or MB, I've always had wrong results. I must have 13gb available ram, when i try to convert it into gb, it gives the output in MB and so on.
```
# Memory
memavail="#{LinuxStat::Memory.available()}"
memfree="#{LinuxStat::Memory.free()}"
memused="#{LinuxStat::Memory.used()}"
memtotal="#{LinuxStat::Memory.total()}"
puts LS::PrettifyBytes.convert_binary(memavail.to_f)
=> 13.46 mebibytes
```

**Comment by Souravgoswami** [comment]
Sorry for the late reply! Oops!

If you see ri documentation for `LinuxStat::Memory.available`:

> = LinuxStat::Memory.available
> (from gem linux_stat-2.6.0)
> === Implementation from Memory
> ------------------------------------------------------------------------
>  available()
>
> ------------------------------------------------------------------------
>
> Returns the total memory details reported by /proc/meminfo. The value is in Kilobyte.
>
> It retuns an Integer but if the info is not available, it will return nil

As you can see it returns value in KB. So you have to multiply the value by 1000 to get the byte size to convert that properly.
